README-FR.md, modules/text/Francais.json, modules/utils/Events.json
***Type :** Suggestion*
**Ajout d'un événement**
J'ai ajouté un événement avec une maison et un forgeron. Voici les différentes possibilités possibles :
* 🔨 Regarder le forgeron
* Le forgeron vous aperçoit et vous propose de vous fabriquer une épée avec lui. Après près d'une heure, votre magnifique épée est refroidie ! [*(Gain du épée)*](https://github.com/YaFou/DraftBot-A-Discord-Adventure/commit/734093e2ec521a11d858ee3dbd4f0be90962808a#r31831927)
* Le forgeron vous aperçoit et vous propose de vous fabriquer une épée avec lui. Malheureusement, le marteau vous tombe dessus d'un coup et vous blesse 😵 !
* Vous regardez le forgeron fabriquer une hache et vous repartez après 10 minutes.
* 💲 Le soutenir en lui donnant un peu d'argent
* Le forgeron vous remercie de votre aide.
* Le forgeron …
=> Ajout d'événement avec une maison de forgeron

modules/text/Francais.json, modules/utils/Events.json
nouvel évent pour le bot, avec des supposés marchands, qui peuvent vous arnaquer, voire être des voleurs déguisés! (on peut essayer de les voler aussi)
évent par DeadAngelV6#6892 et ReallyMinoryo#3959
=> "les marchands de la clairière"

modules/text/Francais.json, modules/utils/Events.json
Le joueur arrive dans une ville abandonnée, avec un chantier au milieu. Il a trois options:
-fouiller le chantier (1-rien 2-trouve un objet ou 3-se blesse)
-fouiller les échafaudages (1-rien 2-trouve un objet 3-se blesse)
-s'en aller(1-rien 2-se blesse en repartant)
(au cas où, les échafaudages sont dans le thème ils en utilisaient déjà au moyen âge)
=> Ajout de l'évent: CHANTIER

modules/text/Francais.json, modules/utils/Events.json
nouvel évent de la team des rédacteurs, rédigé majoritairement par DeadAngelV6#6892 et ReallyMinoryo#1304 (qui adorent les renards)
on y retrouve un mignon renard (mort), mais ayant très faim, on hésite sur quoi faire
=> Ajout de l'évent RENARD MORT

modules/text/Francais.json, modules/utils/Events.json, modules/utils/items/Francais.json
Voilà le gros PULL REQUEST, si tu veux faire des test
=> Ajout des 10 events + Corrections fautes

modules/classes/EquipementManager.js, modules/classes/ObjectManager.js, modules/classes/PotionManager.js, package.json
Salut,
Petite édition du chemin pour le fichier "Tools", et ajout d'info dans le package.json.
Merci, bon taf 👍 :)
=> Tools path fix

modules/text/en.json, modules/text/fr.json, modules/utils/Events.json
Sur une idée de DeadAngelV6#6892, rédigé par IronGab#8038 (qui l'a aussi traduit). Vérification & amélioration de la version fr par ReallyMinoryo#1304, vérification & amélioration de la version en par Dandi_FFH#2450
à la semaine prochaine pour un nouvel évent (peut-être)
=> ajout du premier évent hebdomadaire : marchand itinérant 

modules/text/en.json, modules/text/fr.json, modules/utils/Events.json
évent n°39 : "Price" idée de Price#0398, rédigé et traduit par ReallyMinoryo#1304, traduction corrigée par Thero1st#9119 & Annoying fucking bird#3793
évent n°40 : "Xetrix" idée de Xetrix#0001, rédigé par QuenQuentin#4424, traduit par ReallyMinoryo#1304. Traduction corrigée par Thero1st#9119
=> Ajout des évents donateurs

database/migrations/003-refactor-database-for-next-version.sql, src/core/Database.js
J'ai ajouté des DISTINCT après les SELECT car il y a plusieurs duplications. J'ai aussi override la fonction warning de sequelize pour enlever l'erreur `(sequelize) Warning: Unknown attributes (Player) passed to defaults option of findOrCreate` mais laisser passer les autres qui pourraient être à prendre en compte.
=> Database migration

ressources/text/events/41.json
Correction de l'évent prisonnier, clock + lost time
=> Correctif event prisonnier

ressources/text/events/42.json
=> Event proposal la grotte

src/core/Tools.js
Lorsque l'on accepte un trade du shop on ne récupère la valeur de l'objet dont on se sépare...
Ce pull request fix ce problème.
=> Fix money not given when trade accepted

src/core/MessageError.js
=> Fix frozen effectt

README.md
Correction de quelques erreurs présentes.
=> typo readme

ressources/text/potions/35.json, ressources/text/potions/36.json, ressources/text/potions/37.json, ressources/text/potions/38.json, ressources/text/potions/39.json, ressources/text/potions/40.json
=> fix bug potion shop

ressources/text/commands/listItems.json, ressources/text/commands/shop.json, ressources/text/commands/switch.json, ressources/text/items.json
J'ai modifié tout les items présentes dans la version française (du moins celle que j'ai trouvé) ainsi que j'ai réglé une erreur le texte du shop.
https://github.com/BastLast/DraftBot-A-Discord-Adventure/issues/165
=> Modification appellation #165

src/commands/player/DrinkCommand.js
Cette pr fix le bug issue #206
=> fix potion bug #206

ressources/text/commands/inventory.json, ressources/text/commands/sell.json
Changement des messages de vente d'item et de potion pour clarifier et embellir cf #178
=> Change message #178

ressources/text/events/46.json
Ajout de l'évent n°46 chanson ménestrel
=> Créateur : romain22222
écrivain : romain22222
=> Ajout de l'event 46

ressources/text/commands/profile.json
Apparition d'un nouveau badge pour les vainqueurs de tournoi. #232
=> Ajout d'un badge

resources/text/objects/35.json, resources/text/objects/36.json, resources/text/objects/37.json
Certains objets n'étaient pas affichés correctement (en gras).
=> Fix du nom objets

resources/text/commands/help.json, resources/text/commands/rarity.json, src/commands/player/Rarity.js
Ajout de la commande rarity permettant d'afficher les % de chance de drop d'un objet selon sa rareté.
Issue : #248
=> Ajout commande rarity

resources/text/commands/help.json, resources/text/commands/idea.json, src/commands/player/IdeaCommand.js
Ajout d'une commande envoyant un lien vers le système de suggestion actuel.
Issue : #254
=> Ajout de la commande idea

resources/text/events/20.json
Fix de la réponse qui n'était pas comme la version française.
_Issue liée : #288_
=> Fix event 20

resources/text/events/42.json
Fix de choix en anglais qui n'était pas censé être là.
Issue liée : _Aucune_
=> Fix english choices

resources/text/commands/petFeed.json, resources/text/food.json
=> Fix typo pet

package.json, resources/text/commands/fight.json, resources/text/commands/help.json, resources/text/commands/petSell.json, resources/text/commands/report.json, resources/text/commands/shop.json, resources/text/commands/vote.json, resources/text/events/10.json, resources/text/events/17.json, resources/text/events/20.json, resources/text/events/23.json, resources/text/events/29.json, resources/text/events/34.json, resources/text/events/40.json, resources/text/events/41.json, resources/text/events/42.json, resources/text/events/46.json, resources/text/events/9.json, src/commands/player/VoteCommand.js
=> Correction de typo

src/core/DraftBot.js
Enlève le fait que le shop puisse tomber sur une potion sans effet + petit refact du code.
_Issue principale : #315 
Issue secondaire : #312_
=> Fix potion sans effet dans le shop + Small refact

resources/text/events/41.json
Ajout d'un temps à l'issue n°3 + Fix xp
_Issue liée : #336_
=> Fix issue + xp 

resources/text/commands/idea.json
modification du lien de la commande suggestion #358
=> Fix issue 358

resources/text/weapons/67.json
Rechangement du nom de l'item 67.json #357
=> Fix issue 357

resources/text/commands/petFree.json, src/commands/pets/PetFreeCommand.js
Ajout d'une feature qui donne une viande lorsqu'un pet est libéré avec une proba de 10%
=> Add giveMeat feature when a pet is free

resources/text/commands/class.json, resources/text/commands/guildAdd.json, resources/text/commands/guildShop.json, resources/text/commands/petNickname.json, resources/text/commands/shop.json
Fix typo des majuscules la ou il devrait y avoir des minuscules
=> Fix maj #383

README.md
Changement d'un screen en français pour un en anglais (comme tout le guide)
=> Update screen readme

package.json, resources/text/small_events/class.json
=> Fix rarity class event + Version package 

resources/text/advices.json
=> Add advice

src/core/DraftBot.js
Plus de tirage de potions légendaires et mythiques dans le shop
#411
=> Changements tirage des potions shop

resources/text/objects/59.json
=> Ajout d'un nouvel item donateur

resources/text/advices.json
(oui je sais ya pas de traduction mais osef ya bcp moins de joueurs donc c'est pas grave)
=> Ajout de conseils

resources/text/commands/guildElderRemove.json, src/commands/guild/GuildElderRemoveCommand.js, src/commands/guild/GuildKickCommand.js, src/commands/guild/GuildLeaveCommand.js, src/commands/guild/GuildShopCommand.js, src/commands/player/UnlockCommand.js, src/core/messages/DraftBotReactionMessage.ts, src/core/messages/DraftBotShopMessage.ts, src/core/models/Potions.js
=> Bugfix shop embed ne supportait pas les emotes customs

package.json, resources/text/events/42.json
#659 + Updade version in package.json
=> New meta event 42 + version

resources/text/advices.json, resources/text/commands/drink.json, resources/text/commands/fight.json, resources/text/commands/sell.json, resources/text/commands/switch.json, resources/text/events/5.json, resources/text/items.json, resources/text/smallEvents/findItem.json, resources/text/smallEvents/findPotions.json, resources/text/smallEvents/lottery.json, resources/text/smallEvents/space.json
Fix de toutes les typos dont je m'occupe dans #682 et ajout du conseil pour le lien vers le personnages de #684
=> Fix typos #682 & add advice #684

src/commands/admin/testCommands/Guild/GuildXpTestCommand.js, src/commands/admin/testCommands/Player/ExperienceTestCommand.js, src/commands/guild/GuildDailyCommand.js, src/commands/guild/GuildShopCommand.js, src/commands/pets/PetSellCommand.js, src/commands/player/ReportCommand.js, src/core/models/Guilds.js, src/core/models/Players.js, src/core/smallEvents/lotterySmallEvent.js, src/core/smallEvents/winPersonalXPSmallEvent.js
Fonctions revues :  player addExperience et guild addExperience
=> Permettent d'ajouter de l'xp à la guilde + la faire level up, pareillement sur le player.
Fix également le problème lié à la sortie end du mini-event lottery.
**+ Attention à vos commentaires copiés-collés de fonctions (fixed)**
=> Ajout de deux fonctions + Fix lottery + Fix desc erronée d'une fonction

resources/text/commands/switch.json, src/commands/player/SwitchCommand.js
Résolution de tous les problèmes de texte dans !sw ( par rapport équipé(e))
Ajout du prefix du server à la place du ! dans "30 minutes ont été ajoutées à votre !daily"
=> fix mes conneries sur les sw + fix typo server prefix sur les sw aussi

resources/text/bot.json
=> Ajout disclamer mp #757

resources/text/commands/petNickname.json
Petite erreur de syntaxe sur la commande petnickname
=> Correction syntaxe petNickname : successTitle FR

resources/text/commands/drink.json, resources/text/error.json, src/commands/player/DrinkCommand.js, src/commands/player/DrinkForceCommand.js
Plus de JsonReader sur celui-ci POG
=> add drink validation, drinkforce #838 & refactor DrinkCommand.js

resources/text/commands/missions.json, resources/text/models/players.json, src/core/Constants.ts, src/core/messages/DraftBotMissionsMessage.ts, src/core/models/Player.ts
=> Levelupmessages

config/app.json.default, src/core/Command.js
=> Send all dm from bot's dm with the id linked (userID)

resources/text/commands/missionShop.json, resources/text/models/pets.json, src/commands/mission/MissionShopCommand.ts, src/commands/pets/PetFeedCommand.js, src/core/models/Pet.ts, src/core/models/PetEntity.ts
L'issue #675 sera terminée une fois cette pr merge
=> Veterinaire + bugfix questshop

CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> première version contributing guidelines

src/core/bot/DraftBot.ts
=> fix: update negative-value subtract guard

src/commands/CommandsManager.ts, src/core/messages/DraftBotReactionMessage.ts
précision : aucune trace des blacklists a été trouvé, donc au moment où cette pr est merged, on considèrera que c'est supprimé
=> Refactor handle dms + blacklist removal

resources/text/events/62.json, resources/text/events/63.json
A ajouter à la 2.3.2 milestone
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/issues/967
=> Ajout de nouveaux évents pour la milestone 3.0.1 #967

src/core/utils/MessageUtils.ts
=> Fix crash when MP closed #1218

src/core/missions/MissionsController.ts, src/core/models/Player.ts
=> Fix missions xp overlapping #1216

src/commands/CommandsManager.ts, src/commands/admin/testCommands/Map/MapInfosTestCommand.ts, src/commands/guild/GuildDailyCommand.ts, src/commands/player/FightCommand.ts, src/commands/player/ReportCommand.ts, src/commands/player/ShopCommand.ts, src/commands/player/TopCommand.ts, src/core/Maps.ts, src/core/bot/DraftBot.ts, src/core/bot/index.ts, src/core/database/game/models/Player.ts, src/core/messages/DraftBotShopMessage.ts, src/core/messages/DraftBotTradeMessage.ts, src/core/missions/interfaces/fromPlaceToPlace.ts, src/core/utils/ItemUtils.ts
On va dire que je suis sûr à 50% que c'est corrigé... C'est trop compliqué à tester
=> Map times #1342

resources/text/campaign.json, resources/text/missions/dailyPotionsStock.json, resources/text/missions/fightStreak.json, resources/text/missions/petEarnHealth.json, src/commands/admin/testCommands/Fight/SoloFightTestCommand.ts, src/commands/player/ShopCommand.ts, src/core/fights/FightController.ts, src/core/missions/interfaces/fightStreak.ts, src/core/smallEvents/petSmallEvent.ts
Pas le temps de faire la 60 ce soir
=> Campaign 54 to 59 #1519

src/commands/player/SwitchCommand.ts
Je m'en veux terriblement, c de ma faute dans le renommage des variable du switch.
=> Fix switch with no potions #1657

src/core/bot/DraftBot.ts, src/core/maps/TravelTime.ts, src/core/utils/MessageUtils.ts
=> add verification end travel notification + fix notifications bugs #1673

resources/text/events/11.json, src/core/events/PossibilityOutcome.ts
=> 1701 bug cohrence disparue 

src/commands/CommandsManager.ts, src/core/utils/MessageUtils.ts
=> Fix multi message between shards #1690

resources/text/smallEvents/staffMember.json
=> New people on staffEvent

src/core/fights/fighter/PlayerFighter.ts
Fix de l'issue #1857, fallait juste rajouter des parenthèses à une opération, je vous laisse review et push.
=> fix issue #1857

.github/workflows/dailyAdvice.yml
=> added tips github action

src/core/utils/MessageUtils.ts
Je pense que le bug venait de là, il attendait pas d'envoyer la confirmation de l'envoie avant d'edit l'instance de l'embed
=> Fix bug notifications #2177

resources/text/events/70.json, resources/text/events/71.json, resources/text/events/72.json
cette pull request concerne l'ajout de 3 nouveaux évents au bot, à savoir : 
- 70 - Tombeau - La Dune
- 71 - Ermite du désert - Vallée des Rois
- 72 - tournoi seigneurial - Claire de Ville
pour les personnes ayant participé à ces évents : c'est un peu galère de tout lister là, vu que la rédaction de ces évents est entamée depuis longtemps, mais les contributions sont visibles par le repo Events
=> 3 nouveaux évents

resources/text/campaign.json, resources/text/missions/drinkEnergyPotion.json, src/core/utils/ItemUtils.ts
=> fix: inexisting drinkEnergyPotion mission

resources/text/events/73.json
pôtit évent en route des merveilles, qui était de code 188 sur le repo Events si jamais
=> ajout évent 'arnaque tigres' à la Route des Merveilles

resources/text/armors/52.json, resources/text/armors/58.json, resources/text/armors/59.json, resources/text/armors/60.json, resources/text/armors/61.json, resources/text/objects/28.json, resources/text/objects/3.json, resources/text/objects/4.json, resources/text/objects/50.json, resources/text/objects/62.json, resources/text/objects/64.json, resources/text/objects/67.json, resources/text/objects/82.json, resources/text/objects/83.json, resources/text/objects/84.json, resources/text/objects/85.json, resources/text/objects/86.json, resources/text/objects/87.json, resources/text/objects/88.json, resources/text/potions/90.json, resources/text/potions/91.json, resources/text/potions/92.json, resources/text/potions/93.json, resources/text/weapons/89.json, resources/text/weapons/90.json, resources/text/weapons/91.json, resources/text/weapons/92.json, resources/text/weapons/93.json, resources/text/weapons/94.json
=> Add new items. #1955

Core/config/config.default.toml, Discord/config/config.default.toml
C'est toujours intéressant de mettre des valeurs par défaut pour savoir à quoi s'attendre.
=> Ajout de valeurs par défaut pour les fichiers de configs en exemple

Core/src/core/database/game/models/Player.ts, Core/src/core/smallEvents/botFacts.ts, Core/src/data/Class.ts, Discord/src/packetHandlers/handlers/SmallEventsHandler.ts, Discord/src/utils/ClassUtils.ts, Lang/fr/commands.json, Lang/fr/smallEvents.json, Lib/src/packets/smallEvents/SmallEventBotFactsPacket.ts
=> Small eventbot facts front

Core/src/core/smallEvents/findItem.ts, Discord/src/packetHandlers/handlers/SmallEventsHandler.ts, Lang/fr/smallEvents.json, Lib/src/packets/smallEvents/SmallEventFindItemPacket.ts
=> findItem core + front

Core/src/core/smallEvents/pet.ts, Core/src/core/utils/FoodUtils.ts, Discord/package.json, Discord/src/packetHandlers/handlers/NotificationsHandlers.ts, Discord/src/packetHandlers/handlers/SmallEventsHandler.ts, Discord/src/utils/DisplayUtils.ts, Discord/yarn.lock, Lang/fr/models.json, Lang/fr/smallEvents.json, Lib/src/DraftBotIcons.ts, Lib/src/constants/Constants.ts, Lib/src/constants/PetConstants.ts, Lib/src/packets/smallEvents/SmallEventPetPacket.ts, Lib/src/packets/utils/GiveFoodToGuildPacket.ts, Lib/src/packets/utils/NoFoodSpaceInGuildPacket.ts
=> pet SmallEvent core

Core/src/core/smallEvents/UltimateFoodMerchant.ts, Discord/src/packetHandlers/handlers/SmallEventsHandler.ts, Lang/fr/smallEvents.json, Lib/src/constants/SmallEventConstants.ts, Lib/src/packets/smallEvents/SmallEventUltimateFoodMerchantPacket.ts
=> small event UltimateFoodMerchant core + front

Core/src/commands/admin/testCommands/Player/SkipTutorialTestCommand.ts, Core/src/commands/player/ReportCommand.ts, Core/src/core/maps/Maps.ts, Core/src/core/smallEvents/cart.ts, Core/src/data/MapLink.ts, Discord/src/packetHandlers/handlers/ReactionCollectorHandlers.ts, Discord/src/packetHandlers/handlers/SmallEventsHandler.ts, Discord/src/smallEvents/cart.ts, Discord/src/smallEvents/witch.ts, Lang/fr/error.json, Lang/fr/smallEvents.json, Lib/src/DraftBotIcons.ts, Lib/src/constants/BlockingConstants.ts, Lib/src/constants/SmallEventConstants.ts, Lib/src/packets/interaction/ReactionCollectorCart.ts, Lib/src/packets/smallEvents/SmallEventCartPacket.ts
=> 1st version of cart small event without collectors

Core/src/core/bot/DraftBot.ts, Core/src/core/bot/DraftBotConfig.ts, Core/src/core/database/game/GameDatabase.ts, Core/src/core/database/logs/LogsDatabase.ts, Discord/config/config.default.toml, Discord/package.json, Discord/src/bot/DraftBotShard.ts, Discord/src/commands/CommandsManager.ts, Discord/src/commands/notifications/NotificationsCommand.ts, Discord/src/config/DiscordConfig.ts, Discord/src/database/discord/DiscordDatabase.ts, Discord/src/database/discord/migrations/001-notifications.ts, Discord/src/database/discord/models/NotificationsConfiguration.ts, Discord/src/notifications/NotificationSendType.ts, Discord/yarn.lock, Lang/en/discordBuilder.json, Lang/fr/commands.json, Lang/fr/discordBuilder.json, Lib/package.json, Lib/src/DraftBotIcons.ts, Lib/src/database/Database.ts, Lib/src/database/DatabaseConfiguration.ts, Lib/src/utils/StringUtils.ts, Lib/yarn.lock
Pour l'instant il n'y a que la bdd et la commande discord, le système qui envoie les notifs sera fait dans une 2ème PR
=> Notifications v5

Lib/src/database/Database.ts
=> Fix code for windows native

Core/src/commands/player/FightCommand.ts
J'ai testé et validé avec le debugger
=> Prevent player defending two players at the same time #2855

Core/src/core/fights/FightController.ts, Core/src/core/fights/FightView.ts, Core/src/core/fights/fighter/AiPlayerFighter.ts, Core/src/core/fights/fighter/PlayerFighter.ts, Discord/src/commands/player/FightCommand.ts, Lang/fr/commands.json, Lib/src/packets/fights/FightIntroductionPacket.ts
Add pet display to fight introduction #2429 #2810
Improved performances by caching fighters pets
Removed a useless todo
=> Fights todos

Core/resources/armors/62.json, Core/resources/armors/63.json, Core/resources/objects/90.json, Core/resources/potions/94.json, Core/resources/weapons/95.json, Core/resources/weapons/96.json, Core/resources/weapons/97.json, Lang/fr/models.json
Ajout de la base des items,
Si un contrib passe par là s'il peut tester mes modifs au passage ça serait parfait, pas eu le temps de setup docker et tout le tralala pour tester le tout. **A TESTER**
À voir pour équilibrage via @BastLast
Il faut également rajouter les traductions des autres langues, je n'ai pas de soucis avec ça mais faut voir comment vous faites les traductions actuellement et si on me donne les traductions je peux les ajouter.
=> Ajout des items donateurs #2457

Core/src/core/bot/DraftBot.ts
Le ratio est de 110 points / 7 minutes, si tu veux changer @BastLast go
=> Fight points regen loop

Discord/src/commands/mission/MissionShop.ts, Discord/src/commands/player/DailyBonusCommand.ts, Discord/src/commands/player/ShopCommand.ts, Discord/src/packetHandlers/handlers/commands/pet/PetFeedPacketHandlers.ts, Discord/src/utils/DiscordItemUtils.ts, Lang/fr/commands.json, Lang/fr/events.json, Lang/fr/models.json, Lang/fr/notifications.json, Lang/fr/smallEvents.json
Le reste des typos des JSONs et qui sont répertoriées dans #2775.
=> Typos (part deux) #2775

Core/src/core/smallEvents/witch.ts, Core/src/core/smallEvents/witch/bat.ts, Core/src/core/smallEvents/witch/bigWarm.ts, Core/src/core/smallEvents/witch/blood.ts, Core/src/core/smallEvents/witch/bone.ts, Core/src/core/smallEvents/witch/chicken.ts, Core/src/core/smallEvents/witch/cool.ts, Core/src/core/smallEvents/witch/crystalBall.ts, Core/src/core/smallEvents/witch/distiller.ts, Core/src/core/smallEvents/witch/eye.ts, Core/src/core/smallEvents/witch/frog.ts, Core/src/core/smallEvents/witch/greenApple.ts, Core/src/core/smallEvents/witch/heart.ts, Core/src/core/smallEvents/witch/mushroom.ts, Core/src/core/smallEvents/witch/rat.ts, Core/src/core/smallEvents/witch/redApple.ts, Core/src/core/smallEvents/witch/rose.ts, Core/src/core/smallEvents/witch/scorpion.ts, Core/src/core/smallEvents/witch/smallWarm.ts, Core/src/core/smallEvents/witch/snake.ts, Core/src/core/smallEvents/witch/spider.ts, Core/src/core/smallEvents/witch/teeth.ts, Core/src/core/smallEvents/witch/turtle.ts, Core/src/core/smallEvents/witch/wiltedRose.ts, Core/src/core/smallEvents/witch/worm.ts, Core/src/data/WitchAction.ts, Discord/src/smallEvents/witch.ts, Lang/fr/commands.json, Lang/fr/smallEvents.json, Lib/src/packets/smallEvents/SmallEventWitchPacket.ts
=> fix #2998 + MANY other issues with witch event and refactoring

Core/resources/smallEvents/botFacts.json, Core/src/commands/admin/testCommands/Map/MapInfosTestCommand.ts, Core/src/core/database/logs/LogsDatabase.ts, Core/src/core/fights/FightController.ts, Core/src/core/smallEvents/botFacts.ts, Core/src/core/smallEvents/infoFight.ts, Discord/src/commands/guild/GuildCommand.ts, Discord/src/packetHandlers/handlers/SmallEventsHandler.ts, Discord/src/smallEvents/infoFight.ts, Lang/fr/commands.json, Lang/fr/smallEvents.json, Lib/src/packets/smallEvents/SmallEventInfoFightPacket.ts
le but de cette pr c'est d'enlever les s à info car info c'est invariable en anglais
=> refactor: unify naming conventions for info things
